services:
  api:
    image: codekesh/backend-whisperer:latest
    ports:
      - "5000:8000"
    networks:
      - app-network

  ui:
    build:
      context: .
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=http://localhost:5000

networks:
  app-network:
    driver: bridge
