name: Deploy ArtGalleryDatabase

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t codekesh/frontend-listener .

      - name: Publish Image to docker hub
        run: docker push codekesh/frontend-listener:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull codekesh/frontend-listener:latest
      - name: Delete old container
        run: docker rm -f artgallery-frontend-container
      - name: Run Docker Container
        run: docker run -d -p 3000:3000 --name artgallery-frontend-container codekesh/frontend-listener
